# Generated by Django 4.2.5 on 2023-09-17 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%y/%m/%d/')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('tempo', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilNome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrNome', models.CharField(max_length=100)),
                ('usrSenha', models.CharField(max_length=100)),
                ('usrMail', models.CharField(max_length=100)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrosselApp.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=200)),
                ('carrossel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrosselApp.carousel')),
            ],
        ),
        migrations.AddField(
            model_name='setor',
            name='tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrosselApp.tela'),
        ),
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrosselApp.perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrosselApp.usuario')),
            ],
        ),
    ]
