# Generated by Django 4.2.5 on 2023-09-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosselApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='Conteudo',
        ),
        migrations.RenameModel(
            old_name='Tela',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='carrossel',
            new_name='conteudo',
        ),
    ]
