# Generated by Django 4.2.5 on 2023-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosselApp', '0004_remove_perfil_usuario_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='setor',
            field=models.ManyToManyField(blank=True, related_name='grades_editadas', to='carrosselApp.setor', verbose_name='Setores Onde Aparecerá'),
        ),
    ]
