# Generated by Django 4.2.5 on 2023-09-27 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrosselApp', '0006_setor_usuario_alter_setor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='setores_membros', to=settings.AUTH_USER_MODEL, verbose_name='Selecione os Membros do Setor'),
        ),
    ]
