# Generated by Django 4.2.5 on 2023-10-05 11:54

import carrosselApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrosselApp', '0008_alter_conteudo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('video', 'Vídeo'), ('imagem', 'Imagem')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d/', validators=[carrosselApp.models.validate_video_extension], verbose_name='Vídeo')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Sub-Título')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('duracao', models.PositiveIntegerField(verbose_name='Duração (em segundos)')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='pics/%Y/%m/%d/', validators=[carrosselApp.models.validate_image_extension], verbose_name='Imagem')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Sub-Título')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tempo', models.PositiveBigIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrosselApp.imagem'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrosselApp.video'),
        ),
    ]
