# Generated by Django 4.2.5 on 2023-10-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosselApp', '0009_remove_conteudo_descricao_remove_conteudo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duracao',
        ),
    ]
