# Generated by Django 4.2.5 on 2023-10-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosselApp', '0012_remove_conteudo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tempo',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
