# Generated by Django 4.2.6 on 2023-10-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrosselApp', '0013_video_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('video', 'Vídeo'), ('imagem', 'Imagem'), ('planilha', 'Planilha')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planilha_id', models.CharField(max_length=255, verbose_name='ID da Planilha Google')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Sub-Título')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='planilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrosselApp.planilha'),
        ),
    ]
