# Generated by Django 4.2.6 on 2023-10-24 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrosselApp', '0014_alter_conteudo_tipo_planilha_conteudo_planilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilha',
            name='compartilhada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planilhas_compartilhadas', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhada por'),
        ),
    ]
