# Generated by Django 4.2.6 on 2023-10-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosselApp', '0015_planilha_compartilhada_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilha',
            name='compartilhada_por',
        ),
    ]
