# Generated by Django 4.2.6 on 2023-10-27 14:22

import carrosselApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrosselApp', '0016_remove_planilha_compartilhada_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='graficos/%Y/%m/%d/', validators=[carrosselApp.models.validate_image_extension], verbose_name='Imagem')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='planilha',
            name='tempo',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GraficoPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrosselApp.grafico')),
                ('planilha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrosselApp.planilha')),
            ],
        ),
    ]
