# Generated by Django 4.2.6 on 2023-11-15 22:19

import carrosselApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrosselApp', '0017_grafico_planilha_tempo_graficoplanilha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graficoplanilha',
            name='planilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrosselApp.planilha'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.FileField(upload_to='imagem/%Y/%m/%d/', validators=[carrosselApp.models.validate_image_extension], verbose_name='Imagem'),
        ),
    ]
