# Generated by Django 4.2.6 on 2023-11-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrosselApp', '0018_alter_graficoplanilha_planilha_alter_imagem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graficoplanilha',
            name='planilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrosselApp.planilha'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='planilha',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='video',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
