# Generated by Django 4.2.6 on 2023-10-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0015_rename_extra_data_new_usersocialauth_extra_data'),
        ('usuarios', '0002_alter_perfil_cpf_alter_perfil_nome_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='social_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth', verbose_name='Autenticação Social'),
        ),
    ]
