# Generated by Django 4.2.6 on 2023-11-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_social_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='social_auth',
        ),
    ]
